name: Deploy DEV API

on:
  push:
    branches:
      - "dev"
    paths:
      - 'WatchIT.WebAPI**'
      - 'Dockerfile'
      - '.github/workflows/**'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.NUGET_SOURCE_USERNAME }}
          password: ${{ secrets.NUGET_SOURCE_TOKEN }}
      - name: App Settings Variable Substitution
        uses: microsoft/variable-substitution@v1
        with:
          files: 'WatchIT.WebAPI/appsettings.json'
        env:
          JWT.Key: ${{ secrets.API_KEY }}
          ConnectionStrings.database: ${{ secrets.DEV_DB_CONNECTION_STRING }}
      - name: Build the Docker image
        run: docker build -t ghcr.io/watchitproject/watchit-api:latest --build-arg WATCHIT_API_NUGET_USERNAME=${{secrets.NUGET_SOURCE_USERNAME}} --build-arg WATCHIT_API_NUGET_PASSWORD=${{secrets.NUGET_SOURCE_TOKEN}} --build-arg WATCHIT_CERTIFICATE_PASSWORD=${{secrets.API_CERTIFICATE_PASSWORD}} .
      - name: Publish the Docker image
        run: docker push ghcr.io/watchitproject/watchit-api:latest
  deploy:
    needs: build-and-publish
    runs-on: watchit-dev
    steps:
      - name: Login to GitHub Container Registry
        run: docker login ghcr.io -u ${{secrets.NUGET_SOURCE_USERNAME}} -p ${{ secrets.NUGET_SOURCE_TOKEN }}
      - name: Stop Docker container
        run: docker container stop api
        continue-on-error: true
      - name: Remove Docker container
        run: docker container rm api
        continue-on-error: true
      - name: Remove Docker image
        run: docker image rm ghcr.io/watchitproject/watchit-api:latest
        continue-on-error: true
      - name: Pull Docker image
        run: docker pull ghcr.io/watchitproject/watchit-api:latest
      - name: Run Docker container
        run: docker run --name api -p 10443:443 -p 1080:80 --restart unless-stopped -d ghcr.io/watchitproject/watchit-api:latest
      
